# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/BeamMW/beam-go' # Path to the module's code
  nodeBuildPath: $(system.defaultWorkingDirectory)/beam
  nodeBuildResult: $(system.defaultWorkingDirectory)/beamnode
  CC: gcc-8
  CXX: g++-8

steps:
- task: GoTool@0
  inputs:
    version: 1.13

- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    mkdir -p '$(nodeBuildResult)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the workspace'

- script: |
    go version
    go get -v -t -d ./...
  workingDirectory: '$(modulePath)'
  displayName: 'Pull Go dependencies'

- script: |
    # fire up tests
    cd $(modulePath)/wallet
    export WALLET_ENDPOINT=http://127.0.0.1:5000/api/wallet
    go test
  displayName: 'Run recorded tests'
